DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS friendship;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS mpa;
DROP TABLE IF EXISTS genres;

CREATE TABLE IF NOT EXISTS mpa(
    id       INT AUTO_INCREMENT PRIMARY KEY,
    mpa_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS films(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200) NOT NULL,
    release_date DATE NOT NULL,
    duration     INT NOT NULL,
    mpa_id       INT,
    FOREIGN KEY(mpa_id) REFERENCES mpa(id)
);

CREATE TABLE IF NOT EXISTS users(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    login    VARCHAR(200) NOT NULL,
    name     VARCHAR(255),
    birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS friendship(
    user_id   BIGINT,
    friend_id BIGINT,
    PRIMARY KEY(user_id, friend_id),
    FOREIGN KEY(user_id) REFERENCES users(id),
    FOREIGN KEY(friend_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS likes(
    film_id BIGINT,
    user_id BIGINT,
    PRIMARY KEY(film_id, user_id),
    FOREIGN KEY(film_id) REFERENCES films(id),
    FOREIGN KEY(user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS genres(
    id         INT AUTO_INCREMENT PRIMARY KEY,
    genre_name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS film_genres(
    genre_id INT,
    film_id  BIGINT,
    PRIMARY KEY(genre_id, film_id),
    FOREIGN KEY(genre_id) REFERENCES genres(id),
    FOREIGN KEY(film_id) REFERENCES films(id)
);
